apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: fastapi-demo
spec:
  selector:
    app: mydemoapp
  ports:
    - port: 80         # or any port you want clients to use
      targetPort: 8001 # must match the port your pod listens on
  type: NodePort
