name: Build and Push

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./class/part1_app
          file: ./class/part1_app/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
